### PR TITLE
Adding support for Clips

### PR DESCRIPTION
**Pull request by MurrayMcDonald16**
Hi Pavel, finally got around to this

### CODE REVIEW

**Comment by pavhofman** [comment]
Hi Murray,

thanks a lot! Do we need the whole Toolkit class here? IIRC the existing non-clip code already does the same, maybe extracting a method within our sources?
 The buffer validation is trivial, the format validation - csjsound provider works only with PCM formats, no ULAW/ALAW. I am not with my IDE now, but if you look at the SimpleLine code (and its children), you will find a similar method already. I can take a look at it next week.

Thanks,

Pavel.

**Comment by MurrayMcDonald16** [comment]
Eliminating the need to take the entirety of the ToolKit class.  Restricting SimpleClip to PCM formats.

**Comment by pavhofman** [comment]
Thanks. Please would it be possible to squash the first two commits to avoid having the copied Toolkit class in history?  Just git push --force should do. Thanks a lot.

**Comment by MurrayMcDonald16** [comment]
All squashed together Pavel.  Take care!

**Comment by pavhofman** [comment]
Murray, thanks a lot!

**Pull request merged**
